window.HY_DATA = [
  {
    "id": "istanbulun-fethi",
    "title": "İstanbul'un fethi hangi yıl oldu?",
    "year": 1453,
    "date": "29 Mayıs 1453",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İstanbul'un fethi 1453 yılında gerçekleşti.",
    "detail": "İstanbul, Osmanlı padişahı II. Mehmed döneminde fethedildi. Bu olay, dünya tarihi açısından en çok bilinen dönüm noktalarından biridir.",
    "slug": "istanbulun-fethi-hangi-yil-oldu.html",
    "people": "II. Mehmed"
  },
  {
    "id": "turkiye-cumhuriyeti",
    "title": "Türkiye Cumhuriyeti hangi yıl kuruldu?",
    "year": 1923,
    "date": "29 Ekim 1923",
    "type": "Olaylar",
    "category": "Türkiye",
    "answer": "Türkiye Cumhuriyeti 1923 yılında ilan edildi.",
    "detail": "Cumhuriyet 29 Ekim 1923'te ilan edildi. Bu nedenle Türkiye Cumhuriyeti'nin kuruluş yılı 1923 olarak kabul edilir.",
    "slug": "turkiye-cumhuriyeti-hangi-yil-kuruldu.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "cumhuriyet-ilani",
    "title": "Cumhuriyet hangi yıl ilan edildi?",
    "year": 1923,
    "date": "29 Ekim 1923",
    "type": "Olaylar",
    "category": "Türkiye",
    "answer": "Cumhuriyet 1923 yılında ilan edildi.",
    "detail": "Türkiye'de cumhuriyet yönetimi 29 Ekim 1923'te ilan edildi.",
    "slug": "cumhuriyet-hangi-yil-ilan-edildi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "tbmm-acilisi",
    "title": "TBMM hangi yıl açıldı?",
    "year": 1920,
    "date": "23 Nisan 1920",
    "type": "Olaylar",
    "category": "Türkiye",
    "answer": "TBMM 1920 yılında açıldı.",
    "detail": "Türkiye Büyük Millet Meclisi 23 Nisan 1920'de Ankara'da açıldı.",
    "slug": "tbmm-hangi-yil-acildi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "malazgirt",
    "title": "Malazgirt Savaşı hangi yıl oldu?",
    "year": 1071,
    "date": "26 Ağustos 1071",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Malazgirt Savaşı 1071 yılında oldu.",
    "detail": "Büyük Selçuklu Sultanı Alp Arslan ile Bizans İmparatoru IV. Romanos Diogenes arasında gerçekleşti.",
    "slug": "malazgirt-savasi-hangi-yil-oldu.html",
    "people": "Alp Arslan"
  },
  {
    "id": "ankara-baskent",
    "title": "Ankara hangi yıl başkent oldu?",
    "year": 1923,
    "date": "13 Ekim 1923",
    "type": "Olaylar",
    "category": "Türkiye",
    "answer": "Ankara 1923 yılında başkent oldu.",
    "detail": "Ankara, 13 Ekim 1923 tarihinde Türkiye'nin başkenti ilan edildi.",
    "slug": "ankara-hangi-yil-baskent-oldu.html",
    "people": ""
  },
  {
    "id": "lozan",
    "title": "Lozan Antlaşması hangi yıl imzalandı?",
    "year": 1923,
    "date": "24 Temmuz 1923",
    "type": "Olaylar",
    "category": "Türkiye",
    "answer": "Lozan Antlaşması 1923 yılında imzalandı.",
    "detail": "Lozan Barış Antlaşması 24 Temmuz 1923'te imzalandı.",
    "slug": "lozan-antlasmasi-hangi-yil-imzalandi.html",
    "people": ""
  },
  {
    "id": "atatürk-vefat",
    "title": "Atatürk hangi yıl vefat etti?",
    "year": 1938,
    "date": "10 Kasım 1938",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Mustafa Kemal Atatürk 1938 yılında vefat etti.",
    "detail": "Mustafa Kemal Atatürk, 10 Kasım 1938'de İstanbul Dolmabahçe Sarayı'nda hayatını kaybetti. Ölüm nedeni siroz olarak bilinir.",
    "slug": "ataturk-hangi-yil-vefat-etti.html",
    "people": "Mustafa Kemal Atatürk",
    "cause": "Siroz"
  },
  {
    "id": "baris-manco",
    "title": "Barış Manço hangi yılda vefat etti?",
    "year": 1999,
    "date": "1 Şubat 1999",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Barış Manço 1999 yılında vefat etti.",
    "detail": "Barış Manço, 1 Şubat 1999'da hayatını kaybetti. Yaygın kaynaklarda ölüm nedeni kalp krizi olarak geçer. Türk müziğinin en önemli isimlerinden biri kabul edilir.",
    "slug": "baris-manco-hangi-yilda-vefat-etti.html",
    "people": "Barış Manço",
    "cause": "Kalp krizi"
  },
  {
    "id": "kemal-sunal",
    "title": "Kemal Sunal hangi yıl vefat etti?",
    "year": 2000,
    "date": "3 Temmuz 2000",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Kemal Sunal 2000 yılında vefat etti.",
    "detail": "Kemal Sunal, 3 Temmuz 2000'de uçakta geçirdiği kalp krizi sonucu hayatını kaybetti. Türk sinemasının unutulmaz komedi oyuncularındandır.",
    "slug": "kemal-sunal-hangi-yil-vefat-etti.html",
    "people": "Kemal Sunal",
    "cause": "Kalp krizi"
  },
  {
    "id": "neset-ertas",
    "title": "Neşet Ertaş hangi yıl vefat etti?",
    "year": 2012,
    "date": "25 Eylül 2012",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Neşet Ertaş 2012 yılında vefat etti.",
    "detail": "Neşet Ertaş, 25 Eylül 2012'de hayatını kaybetti. Anadolu müziğinin en önemli temsilcilerinden biri olarak anılır.",
    "slug": "neset-ertas-hangi-yil-vefat-etti.html",
    "people": "Neşet Ertaş",
    "cause": "Kanser tedavisi süreci sonrası"
  },
  {
    "id": "cem-karaca",
    "title": "Cem Karaca hangi yıl vefat etti?",
    "year": 2004,
    "date": "8 Şubat 2004",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Cem Karaca 2004 yılında vefat etti.",
    "detail": "Cem Karaca, 8 Şubat 2004'te hayatını kaybetti. Anadolu rock müziğinin önde gelen isimlerindendir.",
    "slug": "cem-karaca-hangi-yil-vefat-etti.html",
    "people": "Cem Karaca",
    "cause": "Kalp yetmezliği / kalp krizi olarak anılır"
  },
  {
    "id": "zeki-muren",
    "title": "Zeki Müren hangi yıl vefat etti?",
    "year": 1996,
    "date": "24 Eylül 1996",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Zeki Müren 1996 yılında vefat etti.",
    "detail": "Zeki Müren, 24 Eylül 1996'da hayatını kaybetti. Türk sanat müziğinin simge isimlerinden biridir.",
    "slug": "zeki-muren-hangi-yil-vefat-etti.html",
    "people": "Zeki Müren",
    "cause": "Kalp rahatsızlığı"
  },
  {
    "id": "kazim-koyuncu",
    "title": "Kazım Koyuncu hangi yıl vefat etti?",
    "year": 2005,
    "date": "25 Haziran 2005",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Kazım Koyuncu 2005 yılında vefat etti.",
    "detail": "Kazım Koyuncu, 25 Haziran 2005'te hayatını kaybetti. Karadeniz müziğini modern yorumlarla geniş kitlelere ulaştırdı.",
    "slug": "kazim-koyuncu-hangi-yil-vefat-etti.html",
    "people": "Kazım Koyuncu",
    "cause": "Kanser"
  },
  {
    "id": "tarik-akan",
    "title": "Tarık Akan hangi yıl vefat etti?",
    "year": 2016,
    "date": "16 Eylül 2016",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Tarık Akan 2016 yılında vefat etti.",
    "detail": "Tarık Akan, 16 Eylül 2016'da hayatını kaybetti. Türk sinemasının önemli oyuncularındandır.",
    "slug": "tarik-akan-hangi-yil-vefat-etti.html",
    "people": "Tarık Akan",
    "cause": "Akciğer kanseri"
  },
  {
    "id": "cuneyt-arkin",
    "title": "Cüneyt Arkın hangi yıl vefat etti?",
    "year": 2022,
    "date": "28 Haziran 2022",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Cüneyt Arkın 2022 yılında vefat etti.",
    "detail": "Cüneyt Arkın, 28 Haziran 2022'de hayatını kaybetti. Türk sinemasının en tanınan oyuncularından biridir.",
    "slug": "cuneyt-arkin-hangi-yil-vefat-etti.html",
    "people": "Cüneyt Arkın",
    "cause": "Kalp durması olarak bildirilmiştir"
  },
  {
    "id": "ilk-iphone",
    "title": "İlk iPhone hangi yıl çıktı?",
    "year": 2007,
    "date": "9 Ocak 2007",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk iPhone 2007 yılında tanıtıldı.",
    "detail": "Apple'ın ilk iPhone modeli 2007'de tanıtıldı. Akıllı telefon pazarının gelişiminde önemli bir dönüm noktası kabul edilir.",
    "slug": "ilk-iphone-hangi-yil-cikti.html",
    "people": "Steve Jobs"
  },
  {
    "id": "ilk-insan-ay",
    "title": "İlk insan Ay'a hangi yıl çıktı?",
    "year": 1969,
    "date": "20 Temmuz 1969",
    "type": "İlkler",
    "category": "Uzay",
    "answer": "İlk insan Ay'a 1969 yılında çıktı.",
    "detail": "Apollo 11 göreviyle insanlar ilk kez Ay yüzeyinde yürüdü. Neil Armstrong ve Buzz Aldrin Ay'a inen ilk insanlardır.",
    "slug": "ilk-insan-aya-hangi-yil-cikti.html",
    "people": "Neil Armstrong, Buzz Aldrin"
  },
  {
    "id": "covid-baslangic",
    "title": "Covid-19 pandemisi hangi yıl başladı?",
    "year": 2019,
    "date": "2019 sonu",
    "type": "Olaylar",
    "category": "Dünya",
    "answer": "Covid-19 ilk olarak 2019 yılında ortaya çıktı; pandemi ilanı 2020'de yapıldı.",
    "detail": "Covid-19 vakaları 2019 sonunda ortaya çıktı. Dünya çapında pandemi ilanı ise 2020 yılında yapıldı.",
    "slug": "covid-19-pandemisi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "google-kurulus",
    "title": "Google hangi yıl kuruldu?",
    "year": 1998,
    "date": "4 Eylül 1998",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Google 1998 yılında kuruldu.",
    "detail": "Google, Larry Page ve Sergey Brin tarafından 1998 yılında kuruldu.",
    "slug": "google-hangi-yil-kuruldu.html",
    "people": "Larry Page, Sergey Brin"
  },
  {
    "id": "youtube-kurulus",
    "title": "YouTube hangi yıl kuruldu?",
    "year": 2005,
    "date": "2005",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "YouTube 2005 yılında kuruldu.",
    "detail": "YouTube 2005 yılında kuruldu ve kısa sürede dünyanın en büyük video platformlarından biri haline geldi.",
    "slug": "youtube-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "facebook-kurulus",
    "title": "Facebook hangi yıl kuruldu?",
    "year": 2004,
    "date": "2004",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Facebook 2004 yılında kuruldu.",
    "detail": "Facebook 2004 yılında üniversite odaklı bir sosyal ağ olarak başladı ve sonra dünya çapında büyüdü.",
    "slug": "facebook-hangi-yil-kuruldu.html",
    "people": "Mark Zuckerberg"
  },
  {
    "id": "twitter-kurulus",
    "title": "Twitter hangi yıl kuruldu?",
    "year": 2006,
    "date": "2006",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Twitter 2006 yılında kuruldu.",
    "detail": "Twitter, 2006 yılında mikroblog platformu olarak ortaya çıktı. Platform daha sonra X adını aldı.",
    "slug": "twitter-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "instagram-kurulus",
    "title": "Instagram hangi yıl kuruldu?",
    "year": 2010,
    "date": "2010",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Instagram 2010 yılında kuruldu.",
    "detail": "Instagram, 2010 yılında fotoğraf ve video paylaşım uygulaması olarak yayınlandı.",
    "slug": "instagram-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "whatsapp-kurulus",
    "title": "WhatsApp hangi yıl kuruldu?",
    "year": 2009,
    "date": "2009",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "WhatsApp 2009 yılında kuruldu.",
    "detail": "WhatsApp, 2009 yılında mesajlaşma uygulaması olarak kuruldu.",
    "slug": "whatsapp-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "tiktok-global",
    "title": "TikTok hangi yıl çıktı?",
    "year": 2016,
    "date": "2016",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "TikTok 2016 yılında ortaya çıktı.",
    "detail": "TikTok'un temelini oluşturan uygulama 2016 yılında piyasaya çıktı; uluslararası büyümesi sonraki yıllarda hızlandı.",
    "slug": "tiktok-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "ilk-web",
    "title": "İlk web sitesi hangi yıl yayınlandı?",
    "year": 1991,
    "date": "1991",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk web sitesi 1991 yılında yayınlandı.",
    "detail": "World Wide Web'in ilk web sitesi 1991 yılında yayınlandı. Bu, internet tarihinin önemli başlangıçlarından biridir.",
    "slug": "ilk-web-sitesi-hangi-yil-yayinlandi.html",
    "people": "Tim Berners-Lee"
  },
  {
    "id": "fransiz-devrimi-hangi-yil-basladi",
    "title": "Fransız Devrimi hangi yıl başladı?",
    "year": 1789,
    "date": "1789",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Fransız Devrimi 1789 yılında başladı.",
    "detail": "Dünya tarihi açısından modern siyasal dönüşümlerin sembol olaylarından biridir.",
    "slug": "fransiz-devrimi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "birinci-dunya-savasi-hangi-yil-basladi",
    "title": "Birinci Dünya Savaşı hangi yıl başladı?",
    "year": 1914,
    "date": "1914",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Birinci Dünya Savaşı 1914 yılında başladı.",
    "detail": "Savaş 1914'te başladı ve 1918'e kadar sürdü.",
    "slug": "birinci-dunya-savasi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "birinci-dunya-savasi-hangi-yil-bitti",
    "title": "Birinci Dünya Savaşı hangi yıl bitti?",
    "year": 1918,
    "date": "1918",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Birinci Dünya Savaşı 1918 yılında sona erdi.",
    "detail": "Savaşın sona ermesiyle dünya siyasetinde yeni dengeler oluştu.",
    "slug": "birinci-dunya-savasi-hangi-yil-bitti.html",
    "people": ""
  },
  {
    "id": "i-kinci-dunya-savasi-hangi-yil-basladi",
    "title": "İkinci Dünya Savaşı hangi yıl başladı?",
    "year": 1939,
    "date": "1939",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İkinci Dünya Savaşı 1939 yılında başladı.",
    "detail": "Savaş, 1939'da Avrupa'da başladı ve kısa sürede genişledi.",
    "slug": "i-kinci-dunya-savasi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "i-kinci-dunya-savasi-hangi-yil-bitti",
    "title": "İkinci Dünya Savaşı hangi yıl bitti?",
    "year": 1945,
    "date": "1945",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İkinci Dünya Savaşı 1945 yılında sona erdi.",
    "detail": "Savaş 1945'te sona erdi ve savaş sonrası dünya düzeni değişti.",
    "slug": "i-kinci-dunya-savasi-hangi-yil-bitti.html",
    "people": ""
  },
  {
    "id": "birlesmis-milletler-hangi-yil-kuruldu",
    "title": "Birleşmiş Milletler hangi yıl kuruldu?",
    "year": 1945,
    "date": "1945",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Birleşmiş Milletler 1945 yılında kuruldu.",
    "detail": "II. Dünya Savaşı sonrasında uluslararası barış ve iş birliği amacıyla kuruldu.",
    "slug": "birlesmis-milletler-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "nato-hangi-yil-kuruldu",
    "title": "NATO hangi yıl kuruldu?",
    "year": 1949,
    "date": "1949",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "NATO 1949 yılında kuruldu.",
    "detail": "Kuzey Atlantik Antlaşması Örgütü, 1949 yılında kuruldu.",
    "slug": "nato-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "berlin-duvari-hangi-yil-yapildi",
    "title": "Berlin Duvarı hangi yıl yapıldı?",
    "year": 1961,
    "date": "1961",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Berlin Duvarı 1961 yılında inşa edildi.",
    "detail": "Soğuk Savaş döneminin simge yapılarından biri haline geldi.",
    "slug": "berlin-duvari-hangi-yil-yapildi.html",
    "people": ""
  },
  {
    "id": "berlin-duvari-hangi-yil-yikildi",
    "title": "Berlin Duvarı hangi yıl yıkıldı?",
    "year": 1989,
    "date": "1989",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Berlin Duvarı 1989 yılında yıkıldı.",
    "detail": "Duvarın yıkılması Soğuk Savaş'ın bitiş sürecinin simgelerinden biridir.",
    "slug": "berlin-duvari-hangi-yil-yikildi.html",
    "people": ""
  },
  {
    "id": "sovyetler-birligi-hangi-yil-dagildi",
    "title": "Sovyetler Birliği hangi yıl dağıldı?",
    "year": 1991,
    "date": "1991",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Sovyetler Birliği 1991 yılında dağıldı.",
    "detail": "Bu olay Soğuk Savaş sonrası dönemin en önemli gelişmelerinden biridir.",
    "slug": "sovyetler-birligi-hangi-yil-dagildi.html",
    "people": ""
  },
  {
    "id": "marmara-depremi-hangi-yil-oldu",
    "title": "Marmara depremi hangi yıl oldu?",
    "year": 1999,
    "date": "1999",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Marmara depremi 1999 yılında oldu.",
    "detail": "17 Ağustos 1999'da gerçekleşen deprem Türkiye'nin en büyük afetlerinden biridir.",
    "slug": "marmara-depremi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "11-eylul-saldirilari-hangi-yil-oldu",
    "title": "11 Eylül saldırıları hangi yıl oldu?",
    "year": 2001,
    "date": "2001",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "11 Eylül saldırıları 2001 yılında oldu.",
    "detail": "Saldırılar 11 Eylül 2001 tarihinde ABD'de gerçekleşti.",
    "slug": "11-eylul-saldirilari-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "euro-banknot-ve-madeni-paralari-hangi-yil-kullanilmaya-baslandi",
    "title": "Euro banknot ve madeni paraları hangi yıl kullanılmaya başlandı?",
    "year": 2002,
    "date": "2002",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Euro nakit para olarak 2002 yılında kullanılmaya başlandı.",
    "detail": "Euro, Avrupa ülkelerinde nakit dolaşıma 2002 yılında girdi.",
    "slug": "euro-banknot-ve-madeni-paralari-hangi-yil-kullanilmaya-baslandi.html",
    "people": ""
  },
  {
    "id": "kuresel-finans-krizi-hangi-yil-basladi",
    "title": "Küresel finans krizi hangi yıl başladı?",
    "year": 2008,
    "date": "2008",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Küresel finans krizi 2008 yılında başladı.",
    "detail": "2008 krizi dünya ekonomisinde büyük etkiler yarattı.",
    "slug": "kuresel-finans-krizi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "15-temmuz-darbe-girisimi-hangi-yil-oldu",
    "title": "15 Temmuz darbe girişimi hangi yıl oldu?",
    "year": 2016,
    "date": "2016",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "15 Temmuz darbe girişimi 2016 yılında oldu.",
    "detail": "Türkiye'de 15 Temmuz 2016 gecesi darbe girişimi yaşandı.",
    "slug": "15-temmuz-darbe-girisimi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "osmanli-devleti-hangi-yil-kuruldu",
    "title": "Osmanlı Devleti hangi yıl kuruldu?",
    "year": 1299,
    "date": "1299",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Osmanlı Beyliği'nin kuruluş yılı yaygın kabulde 1299'dur.",
    "detail": "Osmanlı Devleti'nin kuruluş yılı olarak en yaygın kullanılan tarih 1299'dur. Kurucu isim Osman Bey olarak kabul edilir.",
    "slug": "osmanli-devleti-hangi-yil-kuruldu.html",
    "people": "Osman Bey"
  },
  {
    "id": "ridaniye-savasi-hangi-yil-oldu",
    "title": "Ridaniye Savaşı hangi yıl oldu?",
    "year": 1517,
    "date": "1517",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Ridaniye Savaşı 1517 yılında oldu.",
    "detail": "Yavuz Sultan Selim döneminde gerçekleşen savaş, Osmanlı'nın Mısır hâkimiyeti açısından önemlidir.",
    "slug": "ridaniye-savasi-hangi-yil-oldu.html",
    "people": "Yavuz Sultan Selim"
  },
  {
    "id": "mohac-meydan-muharebesi-hangi-yil-oldu",
    "title": "Mohaç Meydan Muharebesi hangi yıl oldu?",
    "year": 1526,
    "date": "1526",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Mohaç Meydan Muharebesi 1526 yılında oldu.",
    "detail": "Kanuni Sultan Süleyman döneminde gerçekleşen Mohaç Savaşı, Osmanlı tarihinin önemli askeri başarılarından biridir.",
    "slug": "mohac-meydan-muharebesi-hangi-yil-oldu.html",
    "people": "Kanuni Sultan Süleyman"
  },
  {
    "id": "i-kinci-viyana-kusatmasi-hangi-yil-oldu",
    "title": "İkinci Viyana Kuşatması hangi yıl oldu?",
    "year": 1683,
    "date": "1683",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İkinci Viyana Kuşatması 1683 yılında oldu.",
    "detail": "Osmanlı tarihinin Avrupa seferleri içinde en çok bilinen olaylarından biridir.",
    "slug": "i-kinci-viyana-kusatmasi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "amerika-birlesik-devletleri-hangi-yil-bagimsizligini-ilan-etti",
    "title": "Amerika Birleşik Devletleri hangi yıl bağımsızlığını ilan etti?",
    "year": 1776,
    "date": "1776",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "ABD bağımsızlığını 1776 yılında ilan etti.",
    "detail": "Amerikan Bağımsızlık Bildirgesi 4 Temmuz 1776'da kabul edildi.",
    "slug": "amerika-birlesik-devletleri-hangi-yil-bagimsizligini-ilan-etti.html",
    "people": ""
  },
  {
    "id": "tanzimat-fermani-hangi-yil-ilan-edildi",
    "title": "Tanzimat Fermanı hangi yıl ilan edildi?",
    "year": 1839,
    "date": "1839",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Tanzimat Fermanı 1839 yılında ilan edildi.",
    "detail": "Osmanlı Devleti'nde modernleşme adımlarının önemli dönüm noktalarından biridir.",
    "slug": "tanzimat-fermani-hangi-yil-ilan-edildi.html",
    "people": ""
  },
  {
    "id": "islahat-fermani-hangi-yil-ilan-edildi",
    "title": "Islahat Fermanı hangi yıl ilan edildi?",
    "year": 1856,
    "date": "1856",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Islahat Fermanı 1856 yılında ilan edildi.",
    "detail": "Osmanlı Devleti'nde Tanzimat döneminin önemli düzenlemelerinden biridir.",
    "slug": "islahat-fermani-hangi-yil-ilan-edildi.html",
    "people": ""
  },
  {
    "id": "birinci-mesrutiyet-hangi-yil-ilan-edildi",
    "title": "Birinci Meşrutiyet hangi yıl ilan edildi?",
    "year": 1876,
    "date": "1876",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Birinci Meşrutiyet 1876 yılında ilan edildi.",
    "detail": "Osmanlı Devleti'nde anayasal yönetime geçişin ilk önemli adımlarından biridir.",
    "slug": "birinci-mesrutiyet-hangi-yil-ilan-edildi.html",
    "people": ""
  },
  {
    "id": "i-kinci-mesrutiyet-hangi-yil-ilan-edildi",
    "title": "İkinci Meşrutiyet hangi yıl ilan edildi?",
    "year": 1908,
    "date": "1908",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İkinci Meşrutiyet 1908 yılında ilan edildi.",
    "detail": "Osmanlı siyasi tarihinde önemli bir yönetim değişikliği dönemidir.",
    "slug": "i-kinci-mesrutiyet-hangi-yil-ilan-edildi.html",
    "people": ""
  },
  {
    "id": "canakkale-savasi-hangi-yil-oldu",
    "title": "Çanakkale Savaşı hangi yıl oldu?",
    "year": 1915,
    "date": "1915",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Çanakkale Savaşı 1915 yılında yaşandı.",
    "detail": "Çanakkale Cephesi, Birinci Dünya Savaşı'nın en önemli cephelerinden biridir.",
    "slug": "canakkale-savasi-hangi-yil-oldu.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "kurtulus-savasi-hangi-yil-basladi",
    "title": "Kurtuluş Savaşı hangi yıl başladı?",
    "year": 1919,
    "date": "1919",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Kurtuluş Savaşı'nın başlangıcı olarak 1919 yılı kabul edilir.",
    "detail": "19 Mayıs 1919, Mustafa Kemal'in Samsun'a çıkışıyla milli mücadelenin başlangıç sembolü olarak kabul edilir.",
    "slug": "kurtulus-savasi-hangi-yil-basladi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "saltanat-hangi-yil-kaldirildi",
    "title": "Saltanat hangi yıl kaldırıldı?",
    "year": 1922,
    "date": "1922",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Saltanat 1922 yılında kaldırıldı.",
    "detail": "Türkiye'de saltanat 1 Kasım 1922'de kaldırıldı.",
    "slug": "saltanat-hangi-yil-kaldirildi.html",
    "people": ""
  },
  {
    "id": "halifelik-hangi-yil-kaldirildi",
    "title": "Halifelik hangi yıl kaldırıldı?",
    "year": 1924,
    "date": "1924",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Halifelik 1924 yılında kaldırıldı.",
    "detail": "Halifelik 3 Mart 1924 tarihinde kaldırıldı.",
    "slug": "halifelik-hangi-yil-kaldirildi.html",
    "people": ""
  },
  {
    "id": "harf-devrimi-hangi-yil-yapildi",
    "title": "Harf Devrimi hangi yıl yapıldı?",
    "year": 1928,
    "date": "1928",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Harf Devrimi 1928 yılında yapıldı.",
    "detail": "Türkiye'de Latin esaslı yeni Türk alfabesine geçiş 1928'de gerçekleşti.",
    "slug": "harf-devrimi-hangi-yil-yapildi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "soyadi-kanunu-hangi-yil-cikti",
    "title": "Soyadı Kanunu hangi yıl çıktı?",
    "year": 1934,
    "date": "1934",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Soyadı Kanunu 1934 yılında kabul edildi.",
    "detail": "Türkiye'de herkesin soyadı kullanmasını düzenleyen kanun 1934 yılında kabul edildi.",
    "slug": "soyadi-kanunu-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "hatay-hangi-yil-turkiye-ye-katildi",
    "title": "Hatay hangi yıl Türkiye'ye katıldı?",
    "year": 1938,
    "date": "1938",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Hatay 1939 yılında Türkiye'ye katıldı.",
    "detail": "Hatay Devleti süreci sonrası Hatay'ın Türkiye'ye katılması 1939 yılında gerçekleşti.",
    "slug": "hatay-hangi-yil-turkiye-ye-katildi.html",
    "people": ""
  },
  {
    "id": "turkiye-de-cok-partili-secim-hangi-yil-yapildi",
    "title": "Türkiye'de çok partili seçim hangi yıl yapıldı?",
    "year": 1950,
    "date": "1950",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Türkiye'de çok partili siyasi hayatın önemli seçimlerinden biri 1950 yılında yapıldı.",
    "detail": "1950 seçimleri Türkiye siyasi tarihinde önemli bir dönüm noktasıdır.",
    "slug": "turkiye-de-cok-partili-secim-hangi-yil-yapildi.html",
    "people": ""
  },
  {
    "id": "27-mayis-darbesi-hangi-yil-oldu",
    "title": "27 Mayıs darbesi hangi yıl oldu?",
    "year": 1960,
    "date": "1960",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "27 Mayıs darbesi 1960 yılında oldu.",
    "detail": "Türkiye siyasi tarihinde askeri müdahaleler döneminin ilk örneklerinden biridir.",
    "slug": "27-mayis-darbesi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "kibris-baris-harek-ti-hangi-yil-yapildi",
    "title": "Kıbrıs Barış Harekâtı hangi yıl yapıldı?",
    "year": 1974,
    "date": "1974",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Kıbrıs Barış Harekâtı 1974 yılında yapıldı.",
    "detail": "Türkiye'nin Kıbrıs'a askeri müdahalesi 1974 yılında gerçekleşti.",
    "slug": "kibris-baris-harek-ti-hangi-yil-yapildi.html",
    "people": ""
  },
  {
    "id": "12-eylul-darbesi-hangi-yil-oldu",
    "title": "12 Eylül darbesi hangi yıl oldu?",
    "year": 1980,
    "date": "1980",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "12 Eylül darbesi 1980 yılında oldu.",
    "detail": "Türkiye siyasi tarihinde önemli kırılmalardan biridir.",
    "slug": "12-eylul-darbesi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "gumruk-birligi-hangi-yil-basladi",
    "title": "Gümrük Birliği hangi yıl başladı?",
    "year": 1995,
    "date": "1995",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Türkiye-AB Gümrük Birliği 1995 yılında kabul edildi; uygulama 1996'da başladı.",
    "detail": "Türkiye ile Avrupa Birliği arasındaki Gümrük Birliği süreci ekonomi tarihinde önemli bir başlıktır.",
    "slug": "gumruk-birligi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "ak-parti-hangi-yil-iktidara-geldi",
    "title": "AK Parti hangi yıl iktidara geldi?",
    "year": 2002,
    "date": "2002",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "AK Parti 2002 seçimleri sonrası iktidara geldi.",
    "detail": "3 Kasım 2002 genel seçimleri Türkiye siyasi tarihinde önemli bir dönüm noktasıdır.",
    "slug": "ak-parti-hangi-yil-iktidara-geldi.html",
    "people": ""
  },
  {
    "id": "gezi-parki-olaylari-hangi-yil-oldu",
    "title": "Gezi Parkı olayları hangi yıl oldu?",
    "year": 2013,
    "date": "2013",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Gezi Parkı olayları 2013 yılında oldu.",
    "detail": "Türkiye yakın tarihinde geniş yankı uyandıran toplumsal olaylardan biridir.",
    "slug": "gezi-parki-olaylari-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "covid-19-pandemisi-hangi-yil-pandemi-ilan-edildi",
    "title": "Covid-19 pandemisi hangi yıl pandemi ilan edildi?",
    "year": 2020,
    "date": "2020",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Covid-19 için pandemi ilanı 2020 yılında yapıldı.",
    "detail": "Hastalık 2019 sonunda ortaya çıktı; Dünya Sağlık Örgütü pandemi ilanını 2020'de yaptı.",
    "slug": "covid-19-pandemisi-hangi-yil-pandemi-ilan-edildi.html",
    "people": ""
  },
  {
    "id": "telefon-hangi-yil-icat-edildi",
    "title": "Telefon hangi yıl icat edildi?",
    "year": 1876,
    "date": "1876",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Telefonun icadı için en yaygın kabul edilen yıl 1876'dır.",
    "detail": "Alexander Graham Bell'in telefon patenti 1876 yılıyla ilişkilendirilir.",
    "slug": "telefon-hangi-yil-icat-edildi.html",
    "people": "Alexander Graham Bell"
  },
  {
    "id": "ampul-hangi-yil-icat-edildi",
    "title": "Ampul hangi yıl icat edildi?",
    "year": 1879,
    "date": "1879",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Pratik elektrik ampulü için en yaygın yıl 1879'dur.",
    "detail": "Thomas Edison'un geliştirdiği pratik ampul 1879 yılıyla anılır.",
    "slug": "ampul-hangi-yil-icat-edildi.html",
    "people": "Thomas Edison"
  },
  {
    "id": "i-lk-otomobil-hangi-yil-yapildi",
    "title": "İlk otomobil hangi yıl yapıldı?",
    "year": 1886,
    "date": "1886",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Modern otomobilin başlangıcı için yaygın kabul edilen yıl 1886'dır.",
    "detail": "Karl Benz'in Benz Patent-Motorwagen aracı modern otomobilin ilk örneklerinden kabul edilir.",
    "slug": "i-lk-otomobil-hangi-yil-yapildi.html",
    "people": "Karl Benz"
  },
  {
    "id": "i-lk-motorlu-ucus-hangi-yil-yapildi",
    "title": "İlk motorlu uçuş hangi yıl yapıldı?",
    "year": 1903,
    "date": "1903",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk kontrollü motorlu uçuş 1903 yılında yapıldı.",
    "detail": "Wright Kardeşler'in 1903 uçuşu havacılık tarihinin önemli başlangıcıdır.",
    "slug": "i-lk-motorlu-ucus-hangi-yil-yapildi.html",
    "people": "Wright Kardeşler"
  },
  {
    "id": "i-lk-televizyon-yayini-hangi-yil-yapildi",
    "title": "İlk televizyon yayını hangi yıl yapıldı?",
    "year": 1927,
    "date": "1927",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Televizyon tarihindeki ilk önemli gösterimler 1920'lerin ikinci yarısında gerçekleşti.",
    "detail": "Televizyonun gelişimi tek bir tarihe indirgenmese de 1927 yılı önemli dönüm noktalarından biridir.",
    "slug": "i-lk-televizyon-yayini-hangi-yil-yapildi.html",
    "people": ""
  },
  {
    "id": "transistor-hangi-yil-icat-edildi",
    "title": "Transistör hangi yıl icat edildi?",
    "year": 1947,
    "date": "1947",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Transistör 1947 yılında icat edildi.",
    "detail": "Modern elektronik çağının temel buluşlarından biri kabul edilir.",
    "slug": "transistor-hangi-yil-icat-edildi.html",
    "people": ""
  },
  {
    "id": "i-nternetin-temeli-hangi-yil-atildi",
    "title": "İnternetin temeli hangi yıl atıldı?",
    "year": 1969,
    "date": "1969",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "İnternetin temeli sayılan ARPANET 1969 yılında başladı.",
    "detail": "ARPANET, bugünkü internetin öncüllerinden biri olarak kabul edilir.",
    "slug": "i-nternetin-temeli-hangi-yil-atildi.html",
    "people": ""
  },
  {
    "id": "i-lk-e-posta-hangi-yil-gonderildi",
    "title": "İlk e-posta hangi yıl gönderildi?",
    "year": 1971,
    "date": "1971",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk e-posta 1971 yılında gönderildi.",
    "detail": "Ray Tomlinson'ın gönderdiği e-posta internet iletişim tarihinde önemli bir başlangıçtır.",
    "slug": "i-lk-e-posta-hangi-yil-gonderildi.html",
    "people": "Ray Tomlinson"
  },
  {
    "id": "apple-ii-hangi-yil-cikti",
    "title": "Apple II hangi yıl çıktı?",
    "year": 1977,
    "date": "1977",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Apple II 1977 yılında çıktı.",
    "detail": "Kişisel bilgisayarların yaygınlaşmasında önemli modellerden biridir.",
    "slug": "apple-ii-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "ibm-pc-hangi-yil-cikti",
    "title": "IBM PC hangi yıl çıktı?",
    "year": 1981,
    "date": "1981",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "IBM PC 1981 yılında çıktı.",
    "detail": "Kişisel bilgisayar pazarının gelişiminde önemli bir dönüm noktasıdır.",
    "slug": "ibm-pc-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "windows-hangi-yil-cikti",
    "title": "Windows hangi yıl çıktı?",
    "year": 1985,
    "date": "1985",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Microsoft Windows'un ilk sürümü 1985 yılında çıktı.",
    "detail": "Windows işletim sistemi ailesi 1985'te başladı.",
    "slug": "windows-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "world-wide-web-hangi-yil-ortaya-cikti",
    "title": "World Wide Web hangi yıl ortaya çıktı?",
    "year": 1989,
    "date": "1989",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "World Wide Web fikri 1989 yılında ortaya çıktı.",
    "detail": "Tim Berners-Lee'nin çalışmaları web tarihinin başlangıcı kabul edilir.",
    "slug": "world-wide-web-hangi-yil-ortaya-cikti.html",
    "people": "Tim Berners-Lee"
  },
  {
    "id": "amazon-hangi-yil-kuruldu",
    "title": "Amazon hangi yıl kuruldu?",
    "year": 1995,
    "date": "1995",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Amazon 1994 yılında kuruldu; 1995'te çevrim içi satışa başladı.",
    "detail": "Amazon'un e-ticaret yolculuğu 1990'ların ortasında başladı.",
    "slug": "amazon-hangi-yil-kuruldu.html",
    "people": "Jeff Bezos"
  },
  {
    "id": "netflix-hangi-yil-kuruldu",
    "title": "Netflix hangi yıl kuruldu?",
    "year": 1997,
    "date": "1997",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Netflix 1997 yılında kuruldu.",
    "detail": "Netflix başlangıçta DVD kiralama hizmeti olarak kuruldu.",
    "slug": "netflix-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "gmail-hangi-yil-cikti",
    "title": "Gmail hangi yıl çıktı?",
    "year": 2004,
    "date": "2004",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Gmail 2004 yılında çıktı.",
    "detail": "Google'ın e-posta servisi Gmail 2004 yılında kullanıma sunuldu.",
    "slug": "gmail-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "spotify-hangi-yil-kuruldu",
    "title": "Spotify hangi yıl kuruldu?",
    "year": 2006,
    "date": "2006",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Spotify 2006 yılında kuruldu.",
    "detail": "Spotify, dijital müzik dinleme alışkanlıklarını değiştiren platformlardan biridir.",
    "slug": "spotify-hangi-yil-kuruldu.html",
    "people": ""
  },
  {
    "id": "android-hangi-yil-cikti",
    "title": "Android hangi yıl çıktı?",
    "year": 2008,
    "date": "2008",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Android'in ilk ticari sürümü 2008 yılında çıktı.",
    "detail": "Android mobil işletim sistemi 2008'den itibaren yaygınlaştı.",
    "slug": "android-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "ipad-hangi-yil-cikti",
    "title": "iPad hangi yıl çıktı?",
    "year": 2010,
    "date": "2010",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "iPad 2010 yılında çıktı.",
    "detail": "Apple'ın tablet bilgisayarı iPad 2010 yılında tanıtıldı.",
    "slug": "ipad-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "siri-hangi-yil-cikti",
    "title": "Siri hangi yıl çıktı?",
    "year": 2011,
    "date": "2011",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "Siri 2011 yılında iPhone 4S ile tanıtıldı.",
    "detail": "Sesli asistanların yaygınlaşmasında önemli adımlardan biridir.",
    "slug": "siri-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "chatgpt-hangi-yil-cikti",
    "title": "ChatGPT hangi yıl çıktı?",
    "year": 2022,
    "date": "2022",
    "type": "Olaylar",
    "category": "Teknoloji",
    "answer": "ChatGPT 2022 yılında kullanıma sunuldu.",
    "detail": "ChatGPT, yapay zekâ sohbet araçlarının geniş kitlelere ulaşmasında önemli rol oynadı.",
    "slug": "chatgpt-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "asik-veysel-hangi-yil-vefat-etti",
    "title": "Aşık Veysel hangi yıl vefat etti?",
    "year": 1973,
    "date": "21 Mart 1973",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Aşık Veysel 1973 yılında vefat etti.",
    "detail": "Aşık Veysel, 21 Mart 1973'te hayatını kaybetti. Türk halk şiirinin ve saz geleneğinin en önemli temsilcilerindendir.",
    "slug": "asik-veysel-hangi-yil-vefat-etti.html",
    "people": "Aşık Veysel",
    "cause": "Akciğer kanseri olarak bilinir"
  },
  {
    "id": "nazim-hikmet-hangi-yil-vefat-etti",
    "title": "Nazım Hikmet hangi yıl vefat etti?",
    "year": 1963,
    "date": "3 Haziran 1963",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Nazım Hikmet 1963 yılında vefat etti.",
    "detail": "Nazım Hikmet, 3 Haziran 1963'te hayatını kaybetti. Türk edebiyatının en önemli şairlerinden biridir.",
    "slug": "nazim-hikmet-hangi-yil-vefat-etti.html",
    "people": "Nazım Hikmet",
    "cause": "Kalp krizi"
  },
  {
    "id": "orhan-veli-hangi-yil-vefat-etti",
    "title": "Orhan Veli hangi yıl vefat etti?",
    "year": 1950,
    "date": "14 Kasım 1950",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Orhan Veli 1950 yılında vefat etti.",
    "detail": "Orhan Veli Kanık, 14 Kasım 1950'de hayatını kaybetti. Garip akımının öncü isimlerindendir.",
    "slug": "orhan-veli-hangi-yil-vefat-etti.html",
    "people": "Orhan Veli Kanık",
    "cause": "Beyin kanaması olarak bilinir"
  },
  {
    "id": "yasar-kemal-hangi-yil-vefat-etti",
    "title": "Yaşar Kemal hangi yıl vefat etti?",
    "year": 2015,
    "date": "28 Şubat 2015",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Yaşar Kemal 2015 yılında vefat etti.",
    "detail": "Yaşar Kemal, 28 Şubat 2015'te hayatını kaybetti. Türk edebiyatının dünya çapında tanınan yazarlarındandır.",
    "slug": "yasar-kemal-hangi-yil-vefat-etti.html",
    "people": "Yaşar Kemal",
    "cause": "Çoklu organ yetmezliği olarak bildirilmiştir"
  },
  {
    "id": "turgut-ozal-hangi-yil-vefat-etti",
    "title": "Turgut Özal hangi yıl vefat etti?",
    "year": 1993,
    "date": "17 Nisan 1993",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Turgut Özal 1993 yılında vefat etti.",
    "detail": "Turgut Özal, 17 Nisan 1993'te hayatını kaybetti. Türkiye'nin 8. Cumhurbaşkanıdır.",
    "slug": "turgut-ozal-hangi-yil-vefat-etti.html",
    "people": "Turgut Özal",
    "cause": "Kalp yetmezliği / kalp krizi olarak anılır"
  },
  {
    "id": "bulent-ecevit-hangi-yil-vefat-etti",
    "title": "Bülent Ecevit hangi yıl vefat etti?",
    "year": 2006,
    "date": "5 Kasım 2006",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Bülent Ecevit 2006 yılında vefat etti.",
    "detail": "Bülent Ecevit, 5 Kasım 2006'da hayatını kaybetti. Türkiye siyasi tarihinin önemli isimlerindendir.",
    "slug": "bulent-ecevit-hangi-yil-vefat-etti.html",
    "people": "Bülent Ecevit",
    "cause": "Dolaşım ve solunum yetmezliği olarak bildirilmiştir"
  },
  {
    "id": "suleyman-demirel-hangi-yil-vefat-etti",
    "title": "Süleyman Demirel hangi yıl vefat etti?",
    "year": 2015,
    "date": "17 Haziran 2015",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Süleyman Demirel 2015 yılında vefat etti.",
    "detail": "Süleyman Demirel, 17 Haziran 2015'te hayatını kaybetti. Türkiye'nin 9. Cumhurbaşkanıdır.",
    "slug": "suleyman-demirel-hangi-yil-vefat-etti.html",
    "people": "Süleyman Demirel",
    "cause": "Solunum yolu enfeksiyonu ve kalp yetmezliği olarak bildirilmiştir"
  },
  {
    "id": "muslum-gurses-hangi-yil-vefat-etti",
    "title": "Müslüm Gürses hangi yıl vefat etti?",
    "year": 2013,
    "date": "3 Mart 2013",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Müslüm Gürses 2013 yılında vefat etti.",
    "detail": "Müslüm Gürses, 3 Mart 2013'te hayatını kaybetti. Arabesk müziğin en tanınan isimlerindendir.",
    "slug": "muslum-gurses-hangi-yil-vefat-etti.html",
    "people": "Müslüm Gürses",
    "cause": "Kalp ve akciğer yetmezliği süreci olarak bilinir"
  },
  {
    "id": "kayahan-hangi-yil-vefat-etti",
    "title": "Kayahan hangi yıl vefat etti?",
    "year": 2015,
    "date": "3 Nisan 2015",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Kayahan 2015 yılında vefat etti.",
    "detail": "Kayahan, 3 Nisan 2015'te hayatını kaybetti. Türk pop müziğinin önemli besteci ve yorumcularındandır.",
    "slug": "kayahan-hangi-yil-vefat-etti.html",
    "people": "Kayahan",
    "cause": "Kanser"
  },
  {
    "id": "i-lhan-i-rem-hangi-yil-vefat-etti",
    "title": "İlhan İrem hangi yıl vefat etti?",
    "year": 2022,
    "date": "28 Temmuz 2022",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "İlhan İrem 2022 yılında vefat etti.",
    "detail": "İlhan İrem, 28 Temmuz 2022'de hayatını kaybetti. Türk müziğinin kendine özgü isimlerinden biridir.",
    "slug": "i-lhan-i-rem-hangi-yil-vefat-etti.html",
    "people": "İlhan İrem",
    "cause": "Böbrek rahatsızlığı süreci olarak bildirilmiştir"
  },
  {
    "id": "halit-kivanc-hangi-yil-vefat-etti",
    "title": "Halit Kıvanç hangi yıl vefat etti?",
    "year": 2022,
    "date": "25 Ekim 2022",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Halit Kıvanç 2022 yılında vefat etti.",
    "detail": "Halit Kıvanç, 25 Ekim 2022'de hayatını kaybetti. Türkiye'nin en tanınan sunucu ve gazetecilerindendir.",
    "slug": "halit-kivanc-hangi-yil-vefat-etti.html",
    "people": "Halit Kıvanç",
    "cause": "Yaşa bağlı rahatsızlıklar"
  },
  {
    "id": "dogan-cuceloglu-hangi-yil-vefat-etti",
    "title": "Doğan Cüceloğlu hangi yıl vefat etti?",
    "year": 2021,
    "date": "16 Şubat 2021",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Doğan Cüceloğlu 2021 yılında vefat etti.",
    "detail": "Doğan Cüceloğlu, 16 Şubat 2021'de hayatını kaybetti. Psikoloji ve kişisel gelişim alanındaki çalışmalarıyla tanınır.",
    "slug": "dogan-cuceloglu-hangi-yil-vefat-etti.html",
    "people": "Doğan Cüceloğlu",
    "cause": "Aort damarı yırtılması olarak bildirilmiştir"
  },
  {
    "id": "mina-urgan-hangi-yil-vefat-etti",
    "title": "Mina Urgan hangi yıl vefat etti?",
    "year": 2000,
    "date": "15 Haziran 2000",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Mina Urgan 2000 yılında vefat etti.",
    "detail": "Mina Urgan, 15 Haziran 2000'de hayatını kaybetti. Edebiyatçı ve akademisyen kimliğiyle tanınır.",
    "slug": "mina-urgan-hangi-yil-vefat-etti.html",
    "people": "Mina Urgan"
  },
  {
    "id": "sait-faik-abasiyanik-hangi-yil-vefat-etti",
    "title": "Sait Faik Abasıyanık hangi yıl vefat etti?",
    "year": 1954,
    "date": "11 Mayıs 1954",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Sait Faik Abasıyanık 1954 yılında vefat etti.",
    "detail": "Sait Faik Abasıyanık, 11 Mayıs 1954'te hayatını kaybetti. Türk öykücülüğünün en önemli isimlerindendir.",
    "slug": "sait-faik-abasiyanik-hangi-yil-vefat-etti.html",
    "people": "Sait Faik Abasıyanık",
    "cause": "Siroz"
  },
  {
    "id": "orhan-kemal-hangi-yil-vefat-etti",
    "title": "Orhan Kemal hangi yıl vefat etti?",
    "year": 1970,
    "date": "2 Haziran 1970",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Orhan Kemal 1970 yılında vefat etti.",
    "detail": "Orhan Kemal, 2 Haziran 1970'te hayatını kaybetti. Toplumcu gerçekçi edebiyatın önemli isimlerindendir.",
    "slug": "orhan-kemal-hangi-yil-vefat-etti.html",
    "people": "Orhan Kemal",
    "cause": "Beyin kanaması olarak bilinir"
  },
  {
    "id": "cahit-zarifoglu-hangi-yil-vefat-etti",
    "title": "Cahit Zarifoğlu hangi yıl vefat etti?",
    "year": 1987,
    "date": "7 Haziran 1987",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Cahit Zarifoğlu 1987 yılında vefat etti.",
    "detail": "Cahit Zarifoğlu, 7 Haziran 1987'de hayatını kaybetti. Türk şiirinin önemli isimlerindendir.",
    "slug": "cahit-zarifoglu-hangi-yil-vefat-etti.html",
    "people": "Cahit Zarifoğlu",
    "cause": "Kanser"
  },
  {
    "id": "tomris-uyar-hangi-yil-vefat-etti",
    "title": "Tomris Uyar hangi yıl vefat etti?",
    "year": 2003,
    "date": "4 Temmuz 2003",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Tomris Uyar 2003 yılında vefat etti.",
    "detail": "Tomris Uyar, 4 Temmuz 2003'te hayatını kaybetti. Öykü ve çeviri alanında önemli bir edebiyatçıdır.",
    "slug": "tomris-uyar-hangi-yil-vefat-etti.html",
    "people": "Tomris Uyar",
    "cause": "Kanser"
  },
  {
    "id": "adile-nasit-hangi-yil-vefat-etti",
    "title": "Adile Naşit hangi yıl vefat etti?",
    "year": 1987,
    "date": "11 Aralık 1987",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Adile Naşit 1987 yılında vefat etti.",
    "detail": "Adile Naşit, 11 Aralık 1987'de hayatını kaybetti. Türk sinema ve tiyatrosunun sevilen oyuncularındandır.",
    "slug": "adile-nasit-hangi-yil-vefat-etti.html",
    "people": "Adile Naşit",
    "cause": "Bağırsak kanseri olarak bilinir"
  },
  {
    "id": "munir-ozkul-hangi-yil-vefat-etti",
    "title": "Münir Özkul hangi yıl vefat etti?",
    "year": 2018,
    "date": "5 Ocak 2018",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Münir Özkul 2018 yılında vefat etti.",
    "detail": "Münir Özkul, 5 Ocak 2018'de hayatını kaybetti. Türk tiyatro ve sinemasının usta oyuncularındandır.",
    "slug": "munir-ozkul-hangi-yil-vefat-etti.html",
    "people": "Münir Özkul",
    "cause": "Yaşa bağlı rahatsızlıklar"
  },
  {
    "id": "aysen-gruda-hangi-yil-vefat-etti",
    "title": "Ayşen Gruda hangi yıl vefat etti?",
    "year": 2019,
    "date": "23 Ocak 2019",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Ayşen Gruda 2019 yılında vefat etti.",
    "detail": "Ayşen Gruda, 23 Ocak 2019'da hayatını kaybetti. Türk sinemasının sevilen oyuncularındandır.",
    "slug": "aysen-gruda-hangi-yil-vefat-etti.html",
    "people": "Ayşen Gruda",
    "cause": "Pankreas kanseri"
  },
  {
    "id": "bizans-i-mparatorlugu-hangi-yil-kuruldu",
    "title": "Bizans İmparatorluğu hangi yıl kuruldu?",
    "year": 330,
    "date": "330",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Bizans İmparatorluğu'nun başlangıcı için yaygın kabul edilen tarih 330'dur.",
    "detail": "Konstantinopolis'in Roma İmparatorluğu'nun yeni başkenti yapılması Bizans tarihinin başlangıcıyla ilişkilendirilir.",
    "slug": "bizans-i-mparatorlugu-hangi-yil-kuruldu.html",
    "people": "Konstantin"
  },
  {
    "id": "hicret-hangi-yil-oldu",
    "title": "Hicret hangi yıl oldu?",
    "year": 622,
    "date": "622",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Hicret 622 yılında gerçekleşti.",
    "detail": "Hz. Muhammed'in Mekke'den Medine'ye hicreti İslam takviminin başlangıcı kabul edilir.",
    "slug": "hicret-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "talas-savasi-hangi-yil-oldu",
    "title": "Talas Savaşı hangi yıl oldu?",
    "year": 751,
    "date": "751",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Talas Savaşı 751 yılında oldu.",
    "detail": "Talas Savaşı, Orta Asya tarihi ve Türk-İslam ilişkileri açısından önemli kabul edilir.",
    "slug": "talas-savasi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "dandanakan-savasi-hangi-yil-oldu",
    "title": "Dandanakan Savaşı hangi yıl oldu?",
    "year": 1040,
    "date": "1040",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Dandanakan Savaşı 1040 yılında oldu.",
    "detail": "Büyük Selçuklu Devleti'nin kuruluş sürecindeki önemli savaşlardan biridir.",
    "slug": "dandanakan-savasi-hangi-yil-oldu.html",
    "people": "Tuğrul Bey"
  },
  {
    "id": "hacli-seferleri-hangi-yil-basladi",
    "title": "Haçlı Seferleri hangi yıl başladı?",
    "year": 1096,
    "date": "1096",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Birinci Haçlı Seferi 1096 yılında başladı.",
    "detail": "Haçlı Seferleri Orta Çağ Avrupa ve Yakın Doğu tarihinin önemli olaylarındandır.",
    "slug": "hacli-seferleri-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "magna-carta-hangi-yil-imzalandi",
    "title": "Magna Carta hangi yıl imzalandı?",
    "year": 1215,
    "date": "1215",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Magna Carta 1215 yılında imzalandı.",
    "detail": "İngiltere tarihinde kralın yetkilerini sınırlayan önemli belgelerden biridir.",
    "slug": "magna-carta-hangi-yil-imzalandi.html",
    "people": ""
  },
  {
    "id": "bizans-i-mparatorlugu-hangi-yil-sona-erdi",
    "title": "Bizans İmparatorluğu hangi yıl sona erdi?",
    "year": 1453,
    "date": "1453",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Bizans İmparatorluğu 1453 yılında sona erdi.",
    "detail": "İstanbul'un fethiyle Bizans İmparatorluğu tarih sahnesinden çekildi.",
    "slug": "bizans-i-mparatorlugu-hangi-yil-sona-erdi.html",
    "people": "II. Mehmed"
  },
  {
    "id": "amerika-hangi-yil-kesfedildi",
    "title": "Amerika hangi yıl keşfedildi?",
    "year": 1492,
    "date": "1492",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Amerika'nın Avrupalılar tarafından keşfi için yaygın tarih 1492'dir.",
    "detail": "Kristof Kolomb'un 1492 yolculuğu bu başlıkla anılır; kıtada daha önce yerli halklar yaşamaktaydı.",
    "slug": "amerika-hangi-yil-kesfedildi.html",
    "people": "Kristof Kolomb"
  },
  {
    "id": "reform-hareketi-hangi-yil-basladi",
    "title": "Reform hareketi hangi yıl başladı?",
    "year": 1517,
    "date": "1517",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Reform hareketinin başlangıcı için yaygın kabul edilen yıl 1517'dir.",
    "detail": "Martin Luther'in 1517'de yayımladığı tezler Reform sürecinin sembol başlangıcıdır.",
    "slug": "reform-hareketi-hangi-yil-basladi.html",
    "people": "Martin Luther"
  },
  {
    "id": "preveze-deniz-savasi-hangi-yil-oldu",
    "title": "Preveze Deniz Savaşı hangi yıl oldu?",
    "year": 1538,
    "date": "1538",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Preveze Deniz Savaşı 1538 yılında oldu.",
    "detail": "Barbaros Hayreddin Paşa komutasındaki Osmanlı donanmasının önemli zaferlerinden biridir.",
    "slug": "preveze-deniz-savasi-hangi-yil-oldu.html",
    "people": "Barbaros Hayreddin Paşa"
  },
  {
    "id": "i-nebahti-deniz-savasi-hangi-yil-oldu",
    "title": "İnebahtı Deniz Savaşı hangi yıl oldu?",
    "year": 1571,
    "date": "1571",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İnebahtı Deniz Savaşı 1571 yılında oldu.",
    "detail": "Osmanlı denizcilik tarihindeki önemli savaşlardan biridir.",
    "slug": "i-nebahti-deniz-savasi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "osmanli-safevi-savasi-hangi-yil-basladi",
    "title": "Osmanlı-Safevi Savaşı hangi yıl başladı?",
    "year": 1603,
    "date": "1603",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "1603 yılında Osmanlı-Safevi mücadelesinde yeni dönem başladı.",
    "detail": "Bu başlık Osmanlı-İran ilişkileri ve doğu seferleri bağlamında ele alınır.",
    "slug": "osmanli-safevi-savasi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "karlofca-antlasmasi-hangi-yil-imzalandi",
    "title": "Karlofça Antlaşması hangi yıl imzalandı?",
    "year": 1699,
    "date": "1699",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Karlofça Antlaşması 1699 yılında imzalandı.",
    "detail": "Osmanlı Devleti'nin Avrupa'daki toprak kayıpları açısından önemli bir dönüm noktasıdır.",
    "slug": "karlofca-antlasmasi-hangi-yil-imzalandi.html",
    "people": ""
  },
  {
    "id": "lale-devri-hangi-yil-basladi",
    "title": "Lale Devri hangi yıl başladı?",
    "year": 1718,
    "date": "1718",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Lale Devri 1718 yılında başladı.",
    "detail": "Osmanlı tarihinde kültür, sanat ve yenileşme hareketleriyle anılan dönemdir.",
    "slug": "lale-devri-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "patrona-halil-i-syani-hangi-yil-oldu",
    "title": "Patrona Halil İsyanı hangi yıl oldu?",
    "year": 1730,
    "date": "1730",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Patrona Halil İsyanı 1730 yılında oldu.",
    "detail": "Lale Devri'nin sona ermesiyle ilişkilendirilen önemli Osmanlı olayıdır.",
    "slug": "patrona-halil-i-syani-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "sirp-i-syani-hangi-yil-basladi",
    "title": "Sırp İsyanı hangi yıl başladı?",
    "year": 1804,
    "date": "1804",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Birinci Sırp İsyanı 1804 yılında başladı.",
    "detail": "Osmanlı Balkan tarihi açısından önemli milliyetçi hareketlerden biridir.",
    "slug": "sirp-i-syani-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "yunan-i-syani-hangi-yil-basladi",
    "title": "Yunan İsyanı hangi yıl başladı?",
    "year": 1821,
    "date": "1821",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Yunan İsyanı 1821 yılında başladı.",
    "detail": "Osmanlı Devleti'nden bağımsızlık sürecinde önemli bir olaydır.",
    "slug": "yunan-i-syani-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "yeniceri-ocagi-hangi-yil-kaldirildi",
    "title": "Yeniçeri Ocağı hangi yıl kaldırıldı?",
    "year": 1826,
    "date": "1826",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Yeniçeri Ocağı 1826 yılında kaldırıldı.",
    "detail": "Vaka-i Hayriye olarak bilinen olayla Yeniçeri Ocağı kaldırıldı.",
    "slug": "yeniceri-ocagi-hangi-yil-kaldirildi.html",
    "people": "II. Mahmud"
  },
  {
    "id": "93-harbi-hangi-yil-basladi",
    "title": "93 Harbi hangi yıl başladı?",
    "year": 1877,
    "date": "1877",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "93 Harbi 1877 yılında başladı.",
    "detail": "Osmanlı-Rus Savaşı olarak da bilinen 93 Harbi 1877-1878 yıllarında gerçekleşti.",
    "slug": "93-harbi-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "balkan-savaslari-hangi-yil-basladi",
    "title": "Balkan Savaşları hangi yıl başladı?",
    "year": 1912,
    "date": "1912",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Balkan Savaşları 1912 yılında başladı.",
    "detail": "Osmanlı Devleti'nin Balkanlardaki toprak kayıpları açısından önemli bir dönemdir.",
    "slug": "balkan-savaslari-hangi-yil-basladi.html",
    "people": ""
  },
  {
    "id": "mondros-ateskes-antlasmasi-hangi-yil-imzalandi",
    "title": "Mondros Ateşkes Antlaşması hangi yıl imzalandı?",
    "year": 1918,
    "date": "1918",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Mondros Ateşkes Antlaşması 1918 yılında imzalandı.",
    "detail": "Birinci Dünya Savaşı sonunda Osmanlı Devleti'nin imzaladığı ateşkes antlaşmasıdır.",
    "slug": "mondros-ateskes-antlasmasi-hangi-yil-imzalandi.html",
    "people": ""
  },
  {
    "id": "amasya-genelgesi-hangi-yil-yayimlandi",
    "title": "Amasya Genelgesi hangi yıl yayımlandı?",
    "year": 1919,
    "date": "1919",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Amasya Genelgesi 1919 yılında yayımlandı.",
    "detail": "Milli Mücadele'nin örgütlenme sürecinde önemli bir belgedir.",
    "slug": "amasya-genelgesi-hangi-yil-yayimlandi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "erzurum-kongresi-hangi-yil-toplandi",
    "title": "Erzurum Kongresi hangi yıl toplandı?",
    "year": 1919,
    "date": "1919",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Erzurum Kongresi 1919 yılında toplandı.",
    "detail": "Milli Mücadele döneminin önemli kongrelerinden biridir.",
    "slug": "erzurum-kongresi-hangi-yil-toplandi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "sivas-kongresi-hangi-yil-toplandi",
    "title": "Sivas Kongresi hangi yıl toplandı?",
    "year": 1919,
    "date": "1919",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Sivas Kongresi 1919 yılında toplandı.",
    "detail": "Milli Mücadele'nin ülke çapında örgütlenmesi açısından önemli bir kongredir.",
    "slug": "sivas-kongresi-hangi-yil-toplandi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "sakarya-meydan-muharebesi-hangi-yil-oldu",
    "title": "Sakarya Meydan Muharebesi hangi yıl oldu?",
    "year": 1921,
    "date": "1921",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Sakarya Meydan Muharebesi 1921 yılında oldu.",
    "detail": "Kurtuluş Savaşı'nın dönüm noktalarından biridir.",
    "slug": "sakarya-meydan-muharebesi-hangi-yil-oldu.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "buyuk-taarruz-hangi-yil-basladi",
    "title": "Büyük Taarruz hangi yıl başladı?",
    "year": 1922,
    "date": "1922",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Büyük Taarruz 1922 yılında başladı.",
    "detail": "26 Ağustos 1922'de başlayan Büyük Taarruz, Kurtuluş Savaşı'nın son aşamasıdır.",
    "slug": "buyuk-taarruz-hangi-yil-basladi.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "mudanya-ateskes-antlasmasi-hangi-yil-imzalandi",
    "title": "Mudanya Ateşkes Antlaşması hangi yıl imzalandı?",
    "year": 1922,
    "date": "1922",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Mudanya Ateşkes Antlaşması 1922 yılında imzalandı.",
    "detail": "Kurtuluş Savaşı sonrası siyasi sürece geçişte önemli bir antlaşmadır.",
    "slug": "mudanya-ateskes-antlasmasi-hangi-yil-imzalandi.html",
    "people": ""
  },
  {
    "id": "i-zmir-i-ktisat-kongresi-hangi-yil-toplandi",
    "title": "İzmir İktisat Kongresi hangi yıl toplandı?",
    "year": 1923,
    "date": "1923",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "İzmir İktisat Kongresi 1923 yılında toplandı.",
    "detail": "Yeni Türkiye'nin ekonomik yol haritası açısından önemli bir kongredir.",
    "slug": "i-zmir-i-ktisat-kongresi-hangi-yil-toplandi.html",
    "people": ""
  },
  {
    "id": "turk-dil-kurumu-hangi-yil-kuruldu",
    "title": "Türk Dil Kurumu hangi yıl kuruldu?",
    "year": 1932,
    "date": "1932",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Türk Dil Kurumu 1932 yılında kuruldu.",
    "detail": "Türk dilinin araştırılması ve geliştirilmesi amacıyla kurulmuştur.",
    "slug": "turk-dil-kurumu-hangi-yil-kuruldu.html",
    "people": "Mustafa Kemal Atatürk"
  },
  {
    "id": "ayasofya-hangi-yil-muze-oldu",
    "title": "Ayasofya hangi yıl müze oldu?",
    "year": 1935,
    "date": "1935",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Ayasofya 1935 yılında müze olarak açıldı.",
    "detail": "Ayasofya 1935'te müze statüsüyle ziyarete açıldı; 2020'de yeniden cami olarak ibadete açıldı.",
    "slug": "ayasofya-hangi-yil-muze-oldu.html",
    "people": ""
  },
  {
    "id": "ankara-anlasmasi-hangi-yil-imzalandi",
    "title": "Ankara Anlaşması hangi yıl imzalandı?",
    "year": 1963,
    "date": "1963",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Ankara Anlaşması 1963 yılında imzalandı.",
    "detail": "Türkiye ile Avrupa Ekonomik Topluluğu arasındaki ortaklık sürecinin temel belgelerindendir.",
    "slug": "ankara-anlasmasi-hangi-yil-imzalandi.html",
    "people": ""
  },
  {
    "id": "cernobil-faciasi-hangi-yil-oldu",
    "title": "Çernobil faciası hangi yıl oldu?",
    "year": 1986,
    "date": "1986",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Çernobil faciası 1986 yılında oldu.",
    "detail": "Nükleer enerji tarihinin en büyük kazalarından biri olarak kabul edilir.",
    "slug": "cernobil-faciasi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "turkiye-avrupa-birligi-aday-ulkesi-hangi-yil-oldu",
    "title": "Türkiye Avrupa Birliği aday ülkesi hangi yıl oldu?",
    "year": 1999,
    "date": "1999",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Türkiye 1999 yılında AB aday ülkesi olarak kabul edildi.",
    "detail": "Helsinki Zirvesi'nde Türkiye'nin adaylığı resmen kabul edildi.",
    "slug": "turkiye-avrupa-birligi-aday-ulkesi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "facebook-hangi-yil-yayina-basladi",
    "title": "Facebook hangi yıl yayına başladı?",
    "year": 2004,
    "date": "2004",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Facebook 2004 yılında yayına başladı.",
    "detail": "Facebook, sosyal medya tarihinin en etkili platformlarından biri oldu.",
    "slug": "facebook-hangi-yil-yayina-basladi.html",
    "people": "Mark Zuckerberg"
  },
  {
    "id": "instagram-hangi-yil-cikti",
    "title": "Instagram hangi yıl çıktı?",
    "year": 2010,
    "date": "2010",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Instagram 2010 yılında kullanıma sunuldu.",
    "detail": "Fotoğraf ve video paylaşım uygulaması olarak başlayan Instagram kısa sürede büyüdü.",
    "slug": "instagram-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "turkiye-cumhuriyeti-100-yili-hangi-yil-kutlandi",
    "title": "Türkiye Cumhuriyeti 100. yılı hangi yıl kutlandı?",
    "year": 2023,
    "date": "2023",
    "type": "Olaylar",
    "category": "Tarihi Olaylar",
    "answer": "Türkiye Cumhuriyeti'nin 100. yılı 2023 yılında kutlandı.",
    "detail": "Cumhuriyetin ilanından 100 yıl sonra 2023 yılı yüzüncü yıl olarak kutlandı.",
    "slug": "turkiye-cumhuriyeti-100-yili-hangi-yil-kutlandi.html",
    "people": ""
  },
  {
    "id": "barbaros-hayreddin-pasa-hangi-yil-vefat-etti",
    "title": "Barbaros Hayreddin Paşa hangi yıl vefat etti?",
    "year": 1546,
    "date": "4 Temmuz 1546",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Barbaros Hayreddin Paşa 1546 yılında vefat etti.",
    "detail": "Barbaros Hayreddin Paşa, Osmanlı denizcilik tarihinin en önemli isimlerindendir.",
    "slug": "barbaros-hayreddin-pasa-hangi-yil-vefat-etti.html",
    "people": "Barbaros Hayreddin Paşa"
  },
  {
    "id": "mimar-sinan-hangi-yil-vefat-etti",
    "title": "Mimar Sinan hangi yıl vefat etti?",
    "year": 1588,
    "date": "1588",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Mimar Sinan 1588 yılında vefat etti.",
    "detail": "Mimar Sinan, Osmanlı mimarisinin en büyük isimlerinden biri kabul edilir.",
    "slug": "mimar-sinan-hangi-yil-vefat-etti.html",
    "people": "Mimar Sinan"
  },
  {
    "id": "evliya-celebi-hangi-yil-vefat-etti",
    "title": "Evliya Çelebi hangi yıl vefat etti?",
    "year": 1682,
    "date": "Yaklaşık 1682",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Evliya Çelebi'nin vefat yılı için yaygın kabul 1682'dir.",
    "detail": "Seyahatname adlı eseriyle tanınan Evliya Çelebi'nin ölüm tarihi kaynaklarda yaklaşık olarak verilir.",
    "slug": "evliya-celebi-hangi-yil-vefat-etti.html",
    "people": "Evliya Çelebi",
    "cause": "Net bilgi sınırlıdır"
  },
  {
    "id": "namik-kemal-hangi-yil-vefat-etti",
    "title": "Namık Kemal hangi yıl vefat etti?",
    "year": 1888,
    "date": "2 Aralık 1888",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Namık Kemal 1888 yılında vefat etti.",
    "detail": "Namık Kemal, Türk edebiyatı ve düşünce tarihinde önemli bir isimdir.",
    "slug": "namik-kemal-hangi-yil-vefat-etti.html",
    "people": "Namık Kemal"
  },
  {
    "id": "ziya-gokalp-hangi-yil-vefat-etti",
    "title": "Ziya Gökalp hangi yıl vefat etti?",
    "year": 1924,
    "date": "25 Ekim 1924",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Ziya Gökalp 1924 yılında vefat etti.",
    "detail": "Ziya Gökalp, Türk düşünce hayatının önemli isimlerinden biridir.",
    "slug": "ziya-gokalp-hangi-yil-vefat-etti.html",
    "people": "Ziya Gökalp"
  },
  {
    "id": "mehmet-akif-ersoy-hangi-yil-vefat-etti",
    "title": "Mehmet Akif Ersoy hangi yıl vefat etti?",
    "year": 1936,
    "date": "27 Aralık 1936",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Mehmet Akif Ersoy 1936 yılında vefat etti.",
    "detail": "İstiklal Marşı'nın şairi Mehmet Akif Ersoy 27 Aralık 1936'da hayatını kaybetti.",
    "slug": "mehmet-akif-ersoy-hangi-yil-vefat-etti.html",
    "people": "Mehmet Akif Ersoy"
  },
  {
    "id": "tevfik-fikret-hangi-yil-vefat-etti",
    "title": "Tevfik Fikret hangi yıl vefat etti?",
    "year": 1915,
    "date": "19 Ağustos 1915",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Tevfik Fikret 1915 yılında vefat etti.",
    "detail": "Tevfik Fikret, Servet-i Fünun edebiyatının önemli şairlerindendir.",
    "slug": "tevfik-fikret-hangi-yil-vefat-etti.html",
    "people": "Tevfik Fikret"
  },
  {
    "id": "yahya-kemal-beyatli-hangi-yil-vefat-etti",
    "title": "Yahya Kemal Beyatlı hangi yıl vefat etti?",
    "year": 1958,
    "date": "1 Kasım 1958",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Yahya Kemal Beyatlı 1958 yılında vefat etti.",
    "detail": "Yahya Kemal, Türk şiirinin önemli isimlerinden biridir.",
    "slug": "yahya-kemal-beyatli-hangi-yil-vefat-etti.html",
    "people": "Yahya Kemal Beyatlı"
  },
  {
    "id": "ahmet-hamdi-tanpinar-hangi-yil-vefat-etti",
    "title": "Ahmet Hamdi Tanpınar hangi yıl vefat etti?",
    "year": 1962,
    "date": "24 Ocak 1962",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Ahmet Hamdi Tanpınar 1962 yılında vefat etti.",
    "detail": "Ahmet Hamdi Tanpınar, edebiyat ve düşünce dünyasının önemli isimlerindendir.",
    "slug": "ahmet-hamdi-tanpinar-hangi-yil-vefat-etti.html",
    "people": "Ahmet Hamdi Tanpınar",
    "cause": "Kalp krizi"
  },
  {
    "id": "peyami-safa-hangi-yil-vefat-etti",
    "title": "Peyami Safa hangi yıl vefat etti?",
    "year": 1961,
    "date": "15 Haziran 1961",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Peyami Safa 1961 yılında vefat etti.",
    "detail": "Peyami Safa, Türk roman ve fikir dünyasının önemli isimlerindendir.",
    "slug": "peyami-safa-hangi-yil-vefat-etti.html",
    "people": "Peyami Safa"
  },
  {
    "id": "sabahattin-ali-hangi-yil-vefat-etti",
    "title": "Sabahattin Ali hangi yıl vefat etti?",
    "year": 1948,
    "date": "2 Nisan 1948",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Sabahattin Ali 1948 yılında hayatını kaybetti.",
    "detail": "Sabahattin Ali'nin ölümü 1948 yılında gerçekleşti ve Türkiye edebiyat tarihinde trajik bir olay olarak anılır.",
    "slug": "sabahattin-ali-hangi-yil-vefat-etti.html",
    "people": "Sabahattin Ali",
    "cause": "Öldürülme"
  },
  {
    "id": "cemal-sureya-hangi-yil-vefat-etti",
    "title": "Cemal Süreya hangi yıl vefat etti?",
    "year": 1990,
    "date": "9 Ocak 1990",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Cemal Süreya 1990 yılında vefat etti.",
    "detail": "Cemal Süreya, İkinci Yeni şiirinin en önemli isimlerinden biridir.",
    "slug": "cemal-sureya-hangi-yil-vefat-etti.html",
    "people": "Cemal Süreya"
  },
  {
    "id": "edip-cansever-hangi-yil-vefat-etti",
    "title": "Edip Cansever hangi yıl vefat etti?",
    "year": 1986,
    "date": "28 Mayıs 1986",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Edip Cansever 1986 yılında vefat etti.",
    "detail": "Edip Cansever, modern Türk şiirinin önemli temsilcilerindendir.",
    "slug": "edip-cansever-hangi-yil-vefat-etti.html",
    "people": "Edip Cansever"
  },
  {
    "id": "turgut-uyar-hangi-yil-vefat-etti",
    "title": "Turgut Uyar hangi yıl vefat etti?",
    "year": 1985,
    "date": "22 Ağustos 1985",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Turgut Uyar 1985 yılında vefat etti.",
    "detail": "Turgut Uyar, İkinci Yeni şiirinin önemli şairlerindendir.",
    "slug": "turgut-uyar-hangi-yil-vefat-etti.html",
    "people": "Turgut Uyar"
  },
  {
    "id": "metin-oktay-hangi-yil-vefat-etti",
    "title": "Metin Oktay hangi yıl vefat etti?",
    "year": 1991,
    "date": "13 Eylül 1991",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Metin Oktay 1991 yılında hayatını kaybetti.",
    "detail": "Metin Oktay, Türk futbol tarihinin efsane isimlerinden biridir.",
    "slug": "metin-oktay-hangi-yil-vefat-etti.html",
    "people": "Metin Oktay",
    "cause": "Trafik kazası"
  },
  {
    "id": "sakip-sabanci-hangi-yil-vefat-etti",
    "title": "Sakıp Sabancı hangi yıl vefat etti?",
    "year": 2004,
    "date": "10 Nisan 2004",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Sakıp Sabancı 2004 yılında vefat etti.",
    "detail": "Sakıp Sabancı, Türkiye iş dünyasının tanınan isimlerinden biridir.",
    "slug": "sakip-sabanci-hangi-yil-vefat-etti.html",
    "people": "Sakıp Sabancı",
    "cause": "Böbrek kanseri olarak bilinir"
  },
  {
    "id": "vehbi-koc-hangi-yil-vefat-etti",
    "title": "Vehbi Koç hangi yıl vefat etti?",
    "year": 1996,
    "date": "25 Şubat 1996",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Vehbi Koç 1996 yılında vefat etti.",
    "detail": "Vehbi Koç, Türkiye iş dünyasının en önemli isimlerinden biridir.",
    "slug": "vehbi-koc-hangi-yil-vefat-etti.html",
    "people": "Vehbi Koç"
  },
  {
    "id": "aziz-nesin-hangi-yil-vefat-etti",
    "title": "Aziz Nesin hangi yıl vefat etti?",
    "year": 1995,
    "date": "6 Temmuz 1995",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Aziz Nesin 1995 yılında vefat etti.",
    "detail": "Aziz Nesin, mizah ve edebiyat alanında Türkiye'nin en önemli yazarlarından biridir.",
    "slug": "aziz-nesin-hangi-yil-vefat-etti.html",
    "people": "Aziz Nesin",
    "cause": "Kalp krizi olarak bilinir"
  },
  {
    "id": "rifat-ilgaz-hangi-yil-vefat-etti",
    "title": "Rıfat Ilgaz hangi yıl vefat etti?",
    "year": 1993,
    "date": "7 Temmuz 1993",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Rıfat Ilgaz 1993 yılında vefat etti.",
    "detail": "Rıfat Ilgaz, Hababam Sınıfı'nın yazarı olarak da tanınan önemli edebiyatçıdır.",
    "slug": "rifat-ilgaz-hangi-yil-vefat-etti.html",
    "people": "Rıfat Ilgaz"
  },
  {
    "id": "ugur-mumcu-hangi-yil-hayatini-kaybetti",
    "title": "Uğur Mumcu hangi yıl hayatını kaybetti?",
    "year": 1993,
    "date": "24 Ocak 1993",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Uğur Mumcu 1993 yılında hayatını kaybetti.",
    "detail": "Gazeteci Uğur Mumcu, 24 Ocak 1993'te düzenlenen bombalı saldırı sonucu hayatını kaybetti.",
    "slug": "ugur-mumcu-hangi-yil-hayatini-kaybetti.html",
    "people": "Uğur Mumcu",
    "cause": "Bombalı saldırı"
  },
  {
    "id": "hrant-dink-hangi-yil-hayatini-kaybetti",
    "title": "Hrant Dink hangi yıl hayatını kaybetti?",
    "year": 2007,
    "date": "19 Ocak 2007",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Hrant Dink 2007 yılında hayatını kaybetti.",
    "detail": "Gazeteci Hrant Dink, 19 Ocak 2007'de uğradığı silahlı saldırı sonucu yaşamını yitirdi.",
    "slug": "hrant-dink-hangi-yil-hayatini-kaybetti.html",
    "people": "Hrant Dink",
    "cause": "Silahlı saldırı"
  },
  {
    "id": "kobe-bryant-hangi-yil-hayatini-kaybetti",
    "title": "Kobe Bryant hangi yıl hayatını kaybetti?",
    "year": 2020,
    "date": "26 Ocak 2020",
    "type": "Vefatlar",
    "category": "Kişiler ve Vefat Tarihleri",
    "answer": "Kobe Bryant 2020 yılında hayatını kaybetti.",
    "detail": "Basketbolcu Kobe Bryant, 26 Ocak 2020'de helikopter kazasında yaşamını yitirdi.",
    "slug": "kobe-bryant-hangi-yil-hayatini-kaybetti.html",
    "people": "Kobe Bryant",
    "cause": "Helikopter kazası"
  },
  {
    "id": "matbaa-avrupa-da-hangi-yil-yayginlasti",
    "title": "Matbaa Avrupa'da hangi yıl yaygınlaştı?",
    "year": 1440,
    "date": "1440",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Modern matbaanın Avrupa'daki başlangıcı için 1440'lar kabul edilir.",
    "detail": "Johannes Gutenberg'in çalışmaları matbaa tarihinde önemli dönüm noktasıdır.",
    "slug": "matbaa-avrupa-da-hangi-yil-yayginlasti.html",
    "people": "Johannes Gutenberg"
  },
  {
    "id": "i-lk-teleskop-gozlemleri-hangi-yil-yapildi",
    "title": "İlk teleskop gözlemleri hangi yıl yapıldı?",
    "year": 1609,
    "date": "1609",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Galileo'nun teleskop gözlemleri 1609 yılında başladı.",
    "detail": "Teleskop astronomi tarihinde yeni bir dönemi başlattı.",
    "slug": "i-lk-teleskop-gozlemleri-hangi-yil-yapildi.html",
    "people": "Galileo Galilei"
  },
  {
    "id": "i-lk-cicek-asisi-hangi-yil-yapildi",
    "title": "İlk çiçek aşısı hangi yıl yapıldı?",
    "year": 1796,
    "date": "1796",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk çiçek aşısı 1796 yılında yapıldı.",
    "detail": "Edward Jenner'ın çalışması modern aşılama tarihinin başlangıçlarından kabul edilir.",
    "slug": "i-lk-cicek-asisi-hangi-yil-yapildi.html",
    "people": "Edward Jenner"
  },
  {
    "id": "i-lk-pil-hangi-yil-icat-edildi",
    "title": "İlk pil hangi yıl icat edildi?",
    "year": 1800,
    "date": "1800",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk elektrik pili 1800 yılında icat edildi.",
    "detail": "Alessandro Volta'nın pili elektrik tarihinin önemli buluşudur.",
    "slug": "i-lk-pil-hangi-yil-icat-edildi.html",
    "people": "Alessandro Volta"
  },
  {
    "id": "i-lk-fotograf-hangi-yil-cekildi",
    "title": "İlk fotoğraf hangi yıl çekildi?",
    "year": 1822,
    "date": "1822",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Bilinen ilk kalıcı fotoğraf 1820'lerin ortasında çekildi.",
    "detail": "Fotoğraf tarihi tek bir yıla indirgenmese de 1826/1827 sık kullanılan tarihlerdir.",
    "slug": "i-lk-fotograf-hangi-yil-cekildi.html",
    "people": "Nicéphore Niépce"
  },
  {
    "id": "suveys-kanali-hangi-yil-acildi",
    "title": "Süveyş Kanalı hangi yıl açıldı?",
    "year": 1869,
    "date": "1869",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Süveyş Kanalı 1869 yılında açıldı.",
    "detail": "Akdeniz ile Kızıldeniz'i bağlayan kanal dünya ticareti açısından önemlidir.",
    "slug": "suveys-kanali-hangi-yil-acildi.html",
    "people": ""
  },
  {
    "id": "eyfel-kulesi-hangi-yil-acildi",
    "title": "Eyfel Kulesi hangi yıl açıldı?",
    "year": 1889,
    "date": "1889",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Eyfel Kulesi 1889 yılında açıldı.",
    "detail": "Paris'in simge yapılarından biri olan kule 1889 Dünya Fuarı için inşa edildi.",
    "slug": "eyfel-kulesi-hangi-yil-acildi.html",
    "people": "Gustave Eiffel"
  },
  {
    "id": "sinemanin-ilk-gosterimi-hangi-yil-yapildi",
    "title": "Sinemanın ilk gösterimi hangi yıl yapıldı?",
    "year": 1895,
    "date": "1895",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Sinema tarihindeki ilk halka açık gösterimlerden biri 1895 yılında yapıldı.",
    "detail": "Lumière Kardeşler'in gösterimleri sinema tarihinin başlangıçları arasında sayılır.",
    "slug": "sinemanin-ilk-gosterimi-hangi-yil-yapildi.html",
    "people": "Lumière Kardeşler"
  },
  {
    "id": "ford-model-t-hangi-yil-cikti",
    "title": "Ford Model T hangi yıl çıktı?",
    "year": 1908,
    "date": "1908",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Ford Model T 1908 yılında çıktı.",
    "detail": "Otomobilin kitlesel üretim ve yaygınlaşma sürecinde önemli bir modeldir.",
    "slug": "ford-model-t-hangi-yil-cikti.html",
    "people": "Henry Ford"
  },
  {
    "id": "panama-kanali-hangi-yil-acildi",
    "title": "Panama Kanalı hangi yıl açıldı?",
    "year": 1914,
    "date": "1914",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Panama Kanalı 1914 yılında açıldı.",
    "detail": "Kanal, Atlantik ve Pasifik okyanusları arasında deniz ulaşımını kolaylaştırdı.",
    "slug": "panama-kanali-hangi-yil-acildi.html",
    "people": ""
  },
  {
    "id": "penisilin-hangi-yil-kesfedildi",
    "title": "Penisilin hangi yıl keşfedildi?",
    "year": 1928,
    "date": "1928",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Penisilin 1928 yılında keşfedildi.",
    "detail": "Alexander Fleming'in keşfi tıp tarihinde önemli bir dönüm noktasıdır.",
    "slug": "penisilin-hangi-yil-kesfedildi.html",
    "people": "Alexander Fleming"
  },
  {
    "id": "i-lk-yapay-uydu-hangi-yil-firlatildi",
    "title": "İlk yapay uydu hangi yıl fırlatıldı?",
    "year": 1957,
    "date": "1957",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk yapay uydu 1957 yılında fırlatıldı.",
    "detail": "Sputnik 1, uzay çağının başlangıcı olarak kabul edilir.",
    "slug": "i-lk-yapay-uydu-hangi-yil-firlatildi.html",
    "people": ""
  },
  {
    "id": "i-lk-insan-uzaya-hangi-yil-cikti",
    "title": "İlk insan uzaya hangi yıl çıktı?",
    "year": 1961,
    "date": "1961",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk insan uzaya 1961 yılında çıktı.",
    "detail": "Yuri Gagarin 1961'de uzaya çıkan ilk insan oldu.",
    "slug": "i-lk-insan-uzaya-hangi-yil-cikti.html",
    "people": "Yuri Gagarin"
  },
  {
    "id": "i-lk-video-oyun-konsolu-hangi-yil-cikti",
    "title": "İlk video oyun konsolu hangi yıl çıktı?",
    "year": 1972,
    "date": "1972",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk ticari ev tipi oyun konsollarından biri 1972 yılında çıktı.",
    "detail": "Magnavox Odyssey, ev tipi oyun konsolu tarihinin erken örneklerindendir.",
    "slug": "i-lk-video-oyun-konsolu-hangi-yil-cikti.html",
    "people": ""
  },
  {
    "id": "i-lk-cep-telefonu-gorusmesi-hangi-yil-yapildi",
    "title": "İlk cep telefonu görüşmesi hangi yıl yapıldı?",
    "year": 1973,
    "date": "1973",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "İlk elde taşınabilir cep telefonu görüşmesi 1973 yılında yapıldı.",
    "detail": "Motorola mühendisi Martin Cooper'ın yaptığı görüşme mobil iletişim tarihinde önemlidir.",
    "slug": "i-lk-cep-telefonu-gorusmesi-hangi-yil-yapildi.html",
    "people": "Martin Cooper"
  },
  {
    "id": "i-nternet-tcp-ip-gecisi-hangi-yil-oldu",
    "title": "İnternet TCP/IP geçişi hangi yıl oldu?",
    "year": 1983,
    "date": "1983",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "ARPANET'in TCP/IP'ye geçişi 1983 yılında gerçekleşti.",
    "detail": "Bu tarih internetin teknik gelişiminde önemli bir dönüm noktasıdır.",
    "slug": "i-nternet-tcp-ip-gecisi-hangi-yil-oldu.html",
    "people": ""
  },
  {
    "id": "hubble-uzay-teleskobu-hangi-yil-firlatildi",
    "title": "Hubble Uzay Teleskobu hangi yıl fırlatıldı?",
    "year": 1990,
    "date": "1990",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Hubble Uzay Teleskobu 1990 yılında fırlatıldı.",
    "detail": "Hubble, modern astronominin en önemli gözlem araçlarından biridir.",
    "slug": "hubble-uzay-teleskobu-hangi-yil-firlatildi.html",
    "people": ""
  },
  {
    "id": "google-arama-motoru-hangi-yil-kuruldu",
    "title": "Google arama motoru hangi yıl kuruldu?",
    "year": 1998,
    "date": "1998",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "Google 1998 yılında kuruldu.",
    "detail": "Google, internet arama alışkanlıklarını kökten değiştiren şirketlerden biridir.",
    "slug": "google-arama-motoru-hangi-yil-kuruldu.html",
    "people": "Larry Page, Sergey Brin"
  },
  {
    "id": "youtube-ilk-video-hangi-yil-yuklendi",
    "title": "YouTube ilk video hangi yıl yüklendi?",
    "year": 2005,
    "date": "2005",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "YouTube'a ilk video 2005 yılında yüklendi.",
    "detail": "YouTube'un ilk videosu 2005 yılında platforma yüklendi.",
    "slug": "youtube-ilk-video-hangi-yil-yuklendi.html",
    "people": ""
  },
  {
    "id": "james-webb-uzay-teleskobu-hangi-yil-firlatildi",
    "title": "James Webb Uzay Teleskobu hangi yıl fırlatıldı?",
    "year": 2021,
    "date": "2021",
    "type": "İlkler",
    "category": "Teknoloji",
    "answer": "James Webb Uzay Teleskobu 2021 yılında fırlatıldı.",
    "detail": "Modern astronomi için en gelişmiş uzay teleskoplarından biridir.",
    "slug": "james-webb-uzay-teleskobu-hangi-yil-firlatildi.html",
    "people": ""
  }
];
